package com.yqg.core.model.sql.bankaccount.enums;

import com.google.common.collect.ImmutableList;
import com.yqg.core.service.payment.pp.PaymentProvider;
import lombok.extern.slf4j.Slf4j;

import java.util.List;

@Slf4j
public enum BankType {
  BOC("中国银行"),
  ABC("农业银行"),
  CCB("建设银行"),
  ICBC("工商银行"),
  BOCO("交通银行"),
  CIB("兴业银行"),
  CEB("光大银行"),
  SPDB("上海浦东发展银行"),
  PINGAN("平安银行"),
  CNCB("中信银行"),
  PSBC("邮政储蓄"),
  CGB("广发银行"),
  CMB("招商银行"),
  HXB("华夏银行"),
  BOB("北京银行"),
  BON("南京银行"),
  CMBC("民生银行"),
  SHB("上海银行"),
  SZFZB("深圳发展银行"),
  HFBACNSD("恒丰银行"),

  //以下是泰国的银行
  @Deprecated
  SCB("ธนาคารไทยพาณิชย์"),                                          //泰国汇商银行
  @Deprecated
  KBANK("ธนาคารกสิกรไทย"),                                         //泰国开泰银行
  @Deprecated
  BBL("ธนาคารกรุงเทพ"),                                            //盘谷银行
  @Deprecated
  KTB("ธนาคารกรุงไทย"),                                            //泰京银行
  THAI_BOT("ธนาคารแห่งประเทศไทย"), // Bank of Thailand
  THAI_BBPCL("ธนาคารกรุงเทพจำกัด (มหาชน)"), // Bangkok Bank Public Company Limited
  THAI_KBPCL("ธนาคารกสิกรไทยจำกัด (มหาชน)"), // Kasikornbank Public CompanyLimited
  THAI_RBSNV("เดอะรอยัลแบงก์อ๊อฟสกอตแลนด์เอ็น.วี."), // The Royal Bank of Scotland N.V.
  THAI_KTBPCL("ธนาคารกรุงไทยจำกัด (มหาชน)"), // Krung Thai Bank Public Company Limited
  THAI_JPMCB("ธนาคารเจพี มอร์แกน เชส"), // JP Morgan Chase Bank
  THAI_TTBB("ธนาคารทหารไทยธนชาต จำกัด"), // TTB Bank
  THAI_SCBPCL("ธนาคารไทยพาณิชย์จำกัด (มหาชน)"), // Siam Commercial Bank Public Company Limited
  THAI_CBNA("ธนาคารซิตี้แบงค์"), // Citibank N.A.
  THAI_SMBC("ชูมิโตโม มิตซุยแบงกิ้ง คอร์ ปอเรชั่น"), // Sumitomo Mitsui Banking Corporation
  THAI_SCBTPCL("ธนาคารสแตนดาร์ด ชาร์เตอร์ด (ไทย) จำกัด"), // Standard Chartered Bank (Thai) Public Company Limited
  THAI_CTBPCL("ธนาคารซีไอเอ็มบีไทยจำกัด (มหาชน)"), // CIMB Thai Bank Public Company Limited
  THAI_UOBTPCL("ธนาคารยูโอบีจำกัด (มหาชน)"),// United Overseas Bank (Thai) PCL
  THAI_BAPCL("ธนาคารกรุงศรีอยุธยาจำกัด (มหาชน)"), // Bank of Ayudhya Public Company Limited
  THAI_MICBPCL("ธนาคาร เมกะ สากลพาณิชย์ จำกัด (มหาชน)"), // Mega International Commercial Bank PCL
  THAI_BANA("ธนาคารแห่งอเมริกา เนชั่นแนล แอสโซซิเอชั่น"),  // Bank of America National Association
  THAI_GSB("ธนาคารออมสิน"), // Government Saving Bank
  THAI_HKSHCL("ธนาคารฮ่องกงและเซี่ยงไฮ้แบงกิ้ง คอร์ปอเรชั่น จำกัด"), // Hong Kong & Shanghai Corporation Limited
  THAI_DBA("ธนาคารดอยซ์แบงก์"), // Deutsche Bank Aktiengesellschaft
  THAI_GHB("ธนาคารอาคารสงเคราะห"), // Government Housing Bank
  THAI_BFAAAC("ธนาคารเพื่อการเกษตรและ สหกรณ์การเกษตร"), // Bank for Agriculture and Agricultural Cooperatives
  THAI_MCBL("ธนาคารมิซูโฮ คอร์เปอเรท"), // Mizuho Corporate Bank Limited
  THAI_BNPPB("ธนาคาร บีเอ็นพี พารีบาส์"), // BNP Paribas Bank
  THAI_BOCTPCL("ธนาคารแห่งประเทศจีน (ไทย) จำกัด (มหาชน)"), // Bank of China ( Thai ) Public Company Limited
  THAI_IBOT("ธนาคารอิสลามแห่งประเทศไทย"), // Islamic Bank of Thailand
  THAI_TBPCL("ธนาคารทิสโก้ จำกัด (มหาชน)"), // Tisco Bank Public Company Limited
  THAI_KKBPCL("ธนาคารเกียรตินาคิน จำกัด (มหาชน)"), // Kiatnakin Bank Public Company Limited
  THAI_ICBCTCB("ธนาคารไอซีบีซี(ไทย) จำกัด (มหาชน)"), // ICBC Thai Commercial Bank
  THAI_CRBPCL("ธนาคารไทยเครดิต เพื่อรายย่อย จำกัด (มหาชน)"), // The Thai Credit Retail Bank Public Company Limited
  THAI_LAHBPCL("ธนาคารแลนด์ แอนด์ เฮ้าส์"), // Land and Houses Bank Public Company Limited
  THAI_ABTPCL("ธนาคารเอเอ็นแซด (ไทย) จำกัด (มหาชน)"), // ANZ Bank (Thai) Public Company Limited

  //印尼银行
  BRI("BRI"),                                                     //印尼人民银行
  BCA("BCA"),                                                     //中亚银行
  MANDIRI("BANK MANDIRI"),                                        //曼迪利银行
  BNI("BNI"),                                                     //印尼国家银行
  BII("Maybank"),
  CIMB("Bank CIMB Niaga"),
  PERMATA("Bank Permata"),
  BTN("Bank Tabungan Negara"),
  PANIN("Bank Panin"),
  DKI("Bank DKI"),
  DANAMON("Bank Danamon"),
  MANDIRI_SYR("Syariah Mandiri"),
  BUKOPIN("Bukopin"),
  SINARMAS("Bank Sinarmas"),
  SINARMAS_UUS("Bank Sinarmas UUS"),
  MEGA("Bank Mega"),
  OCBC("OCBC"),
  HSBC("HSBC"),
  HSBC_UUS("HSBC UUS"),
  UOB("UOB"),
  DANA("DANA", true),
  OVO("OVO", true),
  LINKAJA("LinkAja", true),
  GO_PAY("GoPay", true),
  SHOPEE_PAY("ShopeePay", true),

  BSI("Bank Syariah Indonesia"),
  SAQU("Bank Saqu"),

  BTPN("BTPN"),
  BNP("Bank Nusantara Parahyangan"),
  BBI("Bank Bisnis Internasional"),
  BVI("Bank Victoria Internasional"),
  BKE("Bank Seabank Indonesia"),
  BPD_KB_UUS("BPD Kalimantan Barat UUS"),
  BHI("Allo Bank Indonesia"),
  BPD_NTB("BPD Nusa Tenggara Barat"),
  AGRONIAGA("Bank Raya Indonesia"),
  BPD_NTT("BPD Nusa Tenggara Timur"),
  COMMONWEALTH("Bank Commonwealth"),
  CTBC_IDN("Bank Chinatrust Indonesia"),
  BNP_PARIBAS("Bank BNP Paribas"),
  BIS("Bank Index Selindo"),
  BER("Bank Ekonomi Raharja"),
  BJJ("PT Bank Saqu Indonesia"),
  BMD("Bank Mestika Dharma"),
  BME("Bank Metro Express"),
  BMAS("Bank Multi Arta Sentosa"),
  MNC_INTER("Bank MNC Internasional"),
  BSB("Bank Syariah Bukopin"),
  BN("Bank Nationalnobu"),
  BSS("Bank Sahabat Sampoerna"),
  BSHB("Bank Sinar Harapan Bali"),
  BTPN_UUS("Bank Tabungan Pensiunan Nasional UUS"),
  BPD_JTE("BPD Jawa Tengah"),
  BYB("Bank Neo Commerce"),
  BNC("Bank Neo Commerce"),
  BPD_DIY("BPD Daerah Istimewa Yogyakarta"),
  BVS("Bank Victoria Syariah"),
  BPD_KB("BPD Kalimantan Barat"),
  BPD_KTE("BPD Kalimantan Tengah"),
  BPD_KTI("BPD Kalimantan Timur"),
  BPD_KTI_UUS("BPD Kalimantan Timur UUS"),
  BPD_RDK("BPD Riau Dan Kepri"),
  BPD_KS("BPD Kalimantan Selatan"),
  BPD_S("BPD Sulselbar"),
  BPD_SU("BPD Sulawesi"),
  BPD_STENGG("BPD Sulawesi Tenggara"),
  BPD_SB("BPD Sumatera Barat"),
  CNB("Centratama Nasional Bank"),
  BPD_SDB("BPD Sumsel Dan Babel"),
  PMB("Prima Master Bank"),
  STAN_CHAR("Standard Charted Bank"),
  BMSI("Bank Maybank Syariah Indonesia"),
  AIB("Anglomas International Bank"),
  MAYAPADA("Bank Mayapada International"),
  ALADIN("Bank Aladin Syariah"),
  AMAR("Bank Amar Indonesia"),
  MUAMALAT("Bank Muamalat Indonesia"),
  BRII("Bank Rabobank International Indonesia"),
  MEGA_SYR("Bank Syariah Mega"),
  BPD_BE("BPD Bengkulu"),
  BPD_STENGA("BPD Sulawesi Tengah"),
  DEUTSCHE("Deutsche Bank"),
  CITIBANK("Citibank"),
  JPMORGAN("JP Morgan Chase Bank"),
  BSPD("Bank Sahabat Purba Danarta"),
  BBS("Bank BNI Syariah"),
  BRI_SYR("Bank Syariah BRI"),
  BCA_SYR("Bank Central Asia Syariah"),
  BANGKOK("Bangkok Bank"),
  BJB_SYR("Bank BJB Syariah"),
  GANESHA("Bank Ganesha"),
  CAPITAL("Bank Capital Indonesia"),
  MASPION("Bank Maspion Indonesia"),
  BTN_UUS("Bank Tabungan Negara  UUS"),
  BPD_L("BPD Lampung"),
  ARTOS("Bank Jago"),
  ARTHA("Bank Artha Graha International"),
  /**
   * 20250827改名为SuperBank，保留原有枚举，只改前端显示文案
   */
  FAMA("Super Bank Indonesia"),
  MAYORA("Bank Mayora"),
  MIZUHO("Bank Mizuho Indonesia"),
  BOAM("Bank of America Merill-Lynch"),
  TOKYO("Bank of Tokyo Mitsubishi UFJ"),
  RESONA("Bank Resona Perdania"),
  ROYAL("Bank Digital BCA"),
  WINDU("Bank Windu Kentjana Int"),
  MITSUI("Bank Sumitomo Mitsui Indonesia"),
  WOORI("Bank Woori Indonesia"),
  BPD_BA("BPD Bali"),
  BPD_J("BPD Jambi"),
  BPD_KS_UUS("BPD Kalimantan Selatan UUS"),
  BPD_KT_UUS("BPD Kalimantan Timur UUS"),
  BPD_M("BPD Maluku"),
  BPD_P("BPD Papua"),
  BPD_SUL("BPD Sulut"),
  BPD_SDB_UUS("BPD Sumsel Dan Babel UUS"),
  BPD_SUM("BPD Sumut"),
  BAD("Bank Antar Daerah"),
  ANZ("Bank ANZ Indonesia"),
  BJB("Bank BJB"),
  DBS("Bank DBS Indonesia"),
  BBA("Bank Bumi Arta"),
  DINAR_IND("Bank Dinar Indonesia"),
  PUNDI_IND("Bank Pundi Indonesia"),
  QNB_KESAWAN("Bank QNB Kesawan"),
  SBI_IND("Bank SBI Indonesia"),
  BPD_DIY_UUS("BPD Daerah Istimewa Yogyakarta  UUS"),
  BPD_JTE_UUS("BPD Jawa Tengah UUS"),
  BPD_JTI_UUS("BPD Jawa Timur UUS"),
  BPD_SU_UUS("BPD Sulselbar UUS"),
  DANAMON_UUS("Bank Danamon UUS"),
  MUTIARA("Bank Mutiara"),
  PERMATA_UUS("Bank Permata UUS"),
  BHS("Bank Himpunan Saudara 1906"),
  ANDARA("Bank Oke Indonesia"),
  DKI_UUS("Bank DKI UUS"),
  BA("Bank Agris"),
  BPD_JTI("BPD Jawa Timur"),
  CIMB_UUS("Bank CIMB Niaga UUS"),
  HANA("Bank Hana"),
  ICBC_IDN("Bank ICBC Indonesia"),
  BON_UUS("Bank OCBC NISP UUS"),
  BOI_IDN("Bank of India Indonesia"),
  BPD_A("BPD Aceh"),
  BPD_A_UUS("BPD Aceh UUS"),
  BPD_S_UUS("BPD Sumut UUS"),
  RBS("Royal Bank of Scotland"),
  BIP("Bank Ina Perdania"),
  BMN("Bank Mitra Niaga"),
  BPD_SB_UUS("BPD Sumatera Barat UUS"),
  PANIN_SYR("Bank Panin Syariah"),
  BPD_RDK_UUS("BPD Riau Dan Kepri UUS"),
  BEI("Bank Ekspor Indonesia"),
  BANK("Bank Arta Niaga Kencana"),
  BPD_J_UUS("BPD Jambi UUS"),
  BPD_NTB_UUS("BPD Nusa Tenggara Barat UUS"),
  HASBC_UUS("Hongkong and Shanghai Bank Corporation UUS"),

  BPD_BANTEN("BPD Banten"),
  BTPN_SYARIAH("BTPN Syariah"),
  CCB_IND("China Construction Bank Indonesia"),
  EXIMBANK("Indonesia Eximbank"),
  JTRUST("Bank JTrust Indonesia"),
  MANDIRI_TASPEN("Mandiri Taspen Pos"),
  QNB_INDONESIA("Bank QNB Indonesia"),
  SHINHAN("Bank Shinhan Indonesia"),

  // 巴西银行
  BANK_OF_BRAZIL("BCO DO BRASIL SA"),
  CAIXA_FEDERAL("Caixa Econômica Federal"),
  BANK_SANTADER("Banco Santander (Brasil) S. A."),
  BANK_BRADESCO("Banco Bradesco S.A."),
  BANK_ITAU_UNIBANCO("Itaú Unibanco S.A."),

  // 菲律宾银行
  BANCO_DE_ORO("BDO"),
  METRO_BANK("MET"),
  LAND_BANK("LBP"),
  BANK_OF_THE_PHILIPPINE_ISLANDS("BPI"),
  PHILIPPINE_NATIONAL_BANK("PNB"),
  CHINA_BANK("CBC"),
  SECURITY_BANK("SECB"),
  DEVELOPMENT_BANK_OF_THE_PHILIPPINES("DBP"),
  UNION_BANK_OF_THE_PHILIPPINES("UBP"),
  RCBC("RCBC"),
  EAST_WEST_BANK("EWB"),
  CITI_BANK("CTB"),
  ASIA_UNITED_BANK("AUB"),
  HSBC_PH("HSBC"),
  CTBC_BANK("CCB"),
  PHILTRUST_BANK("PTC"),
  BANK_OF_COMMERCE("BOC"),
  MAY_BANK("MYB"),
  ROBINSONS_BANK("RBN"),
  PH_ABP("AllBank Inc"),
  PH_AIB("Amanah Islamic Investment Bank"),
  PH_AUB("Asia United Bank (AUB)"),
  PH_ANZ("Australia and New Zealand Bank"),
  PH_BCH("Bank of China, Ltd. - Manila Branch"),
  PH_BDO("Banco De Oro Unibank, Inc"),
  PH_BKB("Bangkok Bank Public Co, Ltd"),
  PH_BKI("Bangko Kabayan Inc"),
  PH_BMB("Bangko Mabuhay (A Rural Bank), Inc"),
  PH_BNSP("Bangko Nuestra Señora Del Pilar Inc"),
  PH_BOA("Bank of America"),
  PH_BOC("Bank of Commerce"),
  PH_BOF("Bank of Florida"),
  PH_BOM("Bank of Makati"),
  PH_BPI("Bank of the Philippine Islands"),
  PH_BPIDB("BPI Direct BanKO, Inc"),
  PH_BRB("Binangonan Rural Bank (BRBDigital)"),
  PH_CAB("Cantilan Bank"),
  PH_CBB("Country Builders Bank Inc"),
  PH_CBC("China Banking Corporation"),
  PH_CBS("China Bank Savings"),
  PH_CEBRUR("Cebuana Lhuillier Rural Bank, Inc"),
  PH_CIMB("CIMB Bank Philippines"),
  PH_CITI("Citibank"),
  PH_CMG("Camalig Bank"),
  PH_CRBR("Community Rural Bank of Romblon"),
  PH_CRD("CARD Bank"),
  PH_CRDSB("CARD SME Bank, Inc., A Thrift Bank"),
  PH_CTBC("CTBC Bank (Philippines) Corp"),
  PH_DEUTSCHE("Deutsche Bank"),
  PH_DBI("Dungganon Bank (A Microfinance Rural Bank), Inc"),
  PH_DBP("Development Bank of the Philippines"),
  PH_DCDB("Dumaguete City Development Bank"),
  PH_EQB("Equicom Savings Bank, Inc"),
  PH_EWB("East West Banking Corporation"),
  PH_EWR("EastWest Rural Bank or Komo"),
  PH_FBC("First Consolidated Bank Inc"),
  PH_GOTYME("GoTyme Bank"),
  PH_GRB("Guagua Rural Bank Inc"),
  PH_HSBC("Hong Kong and Shanghai Banking Corp"),
  PH_HSBI("HSBC Savings Bank Inc"),
  PH_IBI("Innovative Rural Bank Inc"),
  PH_IBK("Industrial Bank of Korea"),
  PH_ICBC("Industrial and Commercial Bank of China (ICBC) - Manila Branch"),
  PH_ING("ING Bank N.V."),
  PH_ISLA("ISLA Bank"),
  PH_JPM("JP Morgan Chase Bank"),
  PH_KEB("Korea Exchange Bank"),
  PH_KHB("KEB Hana Bank - Manila Branch"),
  PH_LBP("Land Bank of The Philippines"),
  PH_LSB("Legazpi Savings Bank, Inc."),
  PH_MAYA("Maya Bank, Inc."),
  PH_MCCB("Mindanao Consolidated Cooperative Bank"),
  PH_MEGA("Mega International Commercial Bank Co, Ltd."),
  PH_MET("Metropolitan Bank and Trust Company (Metrobank)"),
  PH_MIZUHO("Mizuho Bank, Ltd. - Manila Branch"),
  PH_MPI("Maybank Philippines"),
  PH_MSB("Malayan Bank Savings and Mortgage Bank, Inc."),
  PH_MUFGPH_MUFG("MUFG Bank, Ltd."),
  PH_OMNI("BOmnipay, Inc."),
  PH_ONB("BDO Network Bank"),
  PH_PAR("Partner Rural Bank (Cotabato), Inc."),
  PH_PBB("Philippine Business Bank, Inc., A Savings Bank"),
  PH_PBC("Philippine Bank of Communications (PBCOM)"),
  PH_PNB("Philippine National Bank (PNB)"),
  PH_PRB("Producers Bank"),
  PH_PSB("Philippine Savings Bank (PSBank)"),
  PH_PTC("Philippine Trust Company"),
  PH_PVB("Philippine Veterans Bank"),
  PH_QCB("Queen City Development Bank, Inc."),
  PH_QCRB("Quezon Capital Rural Bank, Inc"),
  PH_RABI("Rang-Ay Bank Inc"),
  PH_RBD("Rural Bank of Digos"),
  PH_RBG("Rural Bank of GuinobatanRural Bank of Guinobatan"),
  PH_RBMI("Rural Bank of Montalban, Inc"),
  PH_RCBC("Rizal Commercial Banking Corporation (RCBC)"),
  PH_ROB("Robinsons Bank"),
  PH_SBA("Sterling Bank of Asia"),
  PH_SCB("Standard Chartered Bank"),
  PH_SEA("Seabank Phillippines Inc."),
  PH_SEC("Security Bank Corporation"),
  PH_SHB("Shinhan Bank - Manila Branch"),
  PH_SMBC("Sumitomo Mitsui Banking Corporation (SMBC)"),
  PH_SSB("Sun Savings Bank"),
  PH_TONIK("Tonik Digital Bank, Inc."),
  PH_TYSB("Tong Yang Savings Bank, Inc."),
  PH_UBP("Union Bank of the Philippines (UBP)"),
  PH_UCBSB("UCPB Savings bank"),
  PH_UCPB("United Coconut Planters Bank (UCPB)"),
  PH_UOB("United Overseas Bank, Ltd. (UOB) - Manila Branch"),
  PH_WDB("Wealth Development Bank Corporation"),
  PH_YUANTA("Yuanta Savings Bank, Inc."),
  PH_USB("UCPB Savings Bank"),
  PH_TYB("Yuanta Savings Bank Philippines, Inc."),
  PH_TRB("Tiaong Rural Bank"),
  PH_RSI("RCBC Savings Bank"),
  PH_RCI("RCBC or DiskarTech"),
  PH_RBN("Robinsons Bank"),
  PH_PPI("Smart e"),
  PH_PBK("Plan Bank"),
  PH_OPI("OMNIPAY, INC."),
  PH_OFB("Overseas Filipino Bank"),
  PH_NLK("Nationlink"),
  PH_LDB("Luzon Development Bank"),
  PH_ERB("Entrepreneur Rural Bank"),
  PH_EBI("Enterprise Bank"),
  PH_DCB("Dumaguete City Rural Bank"),
  PH_CTS("City Savings Bank"),
  PH_CSB("Citystate Savings Bank"),
  PH_BGB("BanKo, a Subsidiary of BPO"),
  PH_BDI("Banco Dipolog"),
  PH_AHB("D Asian Hills Bank"),
  PH_UDP("Union Digital Bank"),
  PH_UNO("UNObank, Inc"),
  // 菲律宾电子钱包
  PH_COINS("Coins.PH", true),
  PH_DCPAY("DCPAY Philippines", true),
  PH_GCASH("GCash", true),
  PH_GRABPAY("GrabPay", true),
  PH_PAYMAYA("PayMaya", true),
  PH_SPY("Starpay Corporation", true),
  PH_JUANCASH("Zybi Tech Inc.", true),
  PH_LULU("Lulu Financial Services (Phils) Inc.", true),
  PH_PPS("PalawanPay", true),
  PH_SHOPEE("ShopeePay", true),
  PH_TAYOCASH("Tayocash Inc.", true),
  PH_USSC("USSC Money Services Inc", true),
  PH_CBCI("CIS Bayad Center, Inc. (CBCI)", true),

  //印度银行
  HDFC("HDFC"),
  AU_SMALL_FINANCE_BANK_LIMITED("AU Small Finance Bank Limited"),
  ABHYUDAYA_COOP_BANK_LTD("Abhyudaya Co-Op Bank Ltd"),
  ABU_DHABI_COMMERCIAL_BANK("Abu Dhabi Commercial Bank"),
  ADITYA_BIRLA_IDEA_PAYMENTS_BANK("Aditya Birla Idea Payments Bank"),
  AHMEDABAD_MERCANTILE_COOP_BANK_LTD("Ahmedabad Mercantile Co-Op Bank Ltd"),
  AIRTEL_PAYMENTS_BANK_LIMITED("Airtel Payments Bank Limited"),
  ALLAHABAD_BANK("Allahabad Bank"),
  ALMORA_URBAN_COOPERATIVE_BANK_LTD("Almora Urban Co-Operative Bank Ltd"),
  AMBARNATH_JAIHIND_COOP_BANK_LTD("Ambarnath Jaihind Coop Bank Ltd"),
  ANDHRA_BANK("Andhra Bank"),
  ANDHRA_PRADESH_GRAMEENA_VIKAS_BANK("Andhra Pradesh Grameena Vikas Bank"),
  ANDHRA_PRAGATHI_GRAMEENA_BANK("Andhra Pragathi Grameena Bank"),
  APNA_SAHAKARI_BANK_LTD("Apna Sahakari Bank Ltd"),
  AUSTARLIA_AND_NEW_ZEALAND_BANKING_GORUP_LTD("Austarlia and New Zealand Banking Gorup Ltd"),
  AXIS_BANK("Axis Bank"),
  BANDHAN_BANK_LIMITED("Bandhan Bank Limited"),
  BANK_INTERNASIONAL_INDONESIA("Bank Internasional Indonesia"),
  BANK_OF_AMERICA("Bank Of America"),
  BANK_OF_BAHRAIN_AND_KUWAIT("Bank Of Bahrain And Kuwait"),
  BANK_OF_BARODA("Bank Of Baroda"),
  BANK_OF_CEYLON("Bank Of Ceylon"),
  BANK_OF_INDIA("Bank Of India"),
  BANK_OF_MAHARASHTRA("Bank Of Maharashtra"),
  BARCLAYS_BANK_PLC("Barclays Bank Plc"),
  BASSEIN_CATHOLIC_COOP_BANK_LTD("Bassein Catholic Co-Op Bank Ltd"),
  BHAGINI_NIVEDITA_SAHAKARI_BANK_LTD("Bhagini Nivedita Sahakari Bank Ltd"),
  BHARAT_COOP_BANK_MUMBAI_LTD("Bharat Co-Op Bank (Mumbai) Ltd"),
  BHARATIYA_MAHILA_BANK_LTD("Bharatiya Mahila Bank Ltd."),
  CANARA_BANK("Canara Bank"),
  CAPITAL_SMALL_FINANCE_BANK_LTD("Capital Small Finance Bank Ltd"),
  CATHOLIC_SYRIAN_BANK_LTD("Catholic Syrian Bank Ltd"),
  CENTRAL_BANK_OF_INDIA("Central Bank Of India"),
  CHINATRUST_COMMERCIAL_BANK("Chinatrust Commercial Bank"),
  CITIZENCREDIT_COOP_BANK_LTD("Citizencredit Co-Op Bank Ltd"),
  CITY_UNION_BANK_LTD("City Union Bank Ltd"),
  COMMONWEALTH_BANK_OF_AUSTRALIA("Commonwealth Bank of Australia"),
  CORPORATION_BANK("Corporation Bank"),
  COSMOS_COOP_BANK_LTD("Cosmos Co-Op Bank Ltd"),
  CREDIT_AGRICOLE_CORP_AND_INVESTMENT_BANK("Credit Agricole Corp and Investment Bank"),
  DMK_JAOLI_BANK("DMK Jaoli Bank"),
  DBS_BANK_LTD("Dbs Bank Ltd"),
  DENA_BANK("Dena Bank"),
  DEOGIRI_NAGARI_SAHAKARI_BANK_LTD("Deogiri Nagari Sahakari Bank Ltd."),
  DEUTSCHE_BANK_AG("Deutsche Bank Ag"),
  DEVELOPMENT_CREDIT_BANK_LTD("Development Credit Bank Ltd"),
  DHANLAXMI_BANK_LTD("Dhanlaxmi Bank Ltd"),
  DICGC("Dicgc"),
  DOHA_BANK_QSC("Doha Bank QSC"),
  DOMBIVLI_NAGARI_SAHAKARI_BANK_LTD("Dombivli Nagari Sahakari Bank Ltd"),
  DURGAPUR_STEEL_PEOPLES_COOPERATIVE_BANK_LTD("Durgapur Steel Peoples Cooperative Bank Ltd"),
  ESAF_SMALL_FINANCE_BANK_LIMITED("ESAF Small Finance Bank Limited"),
  EMIRATES_NBD_BANK_PJSC("Emirates NBD Bank PJSC"),
  EQUITAS_SMALL_FINANCE_BANK_LIMITED("Equitas Small Finance Bank Limited"),
  FEDERAL_BANK_LTD("Federal Bank Ltd"),
  FINCARE_SMALL_FINANCE_BANK_LTD("Fincare Small Finance Bank Ltd"),
  FINO_PAYMENT_BANK("Fino Payment Bank"),
  FIRSTRAND_BANK_LTD("Firstrand Bank Ltd"),
  GREATER_BOMBAY_COOP_BANK_LTD("Greater Bombay Co-Op Bank Ltd"),
  GURGAON_GRAMIN_BANK("Gurgaon Gramin Bank"),
  HDFC_BANK_LTD("Hdfc Bank Ltd"),
  HIMACHAL_PRADESH_STATE_COOPERATIVE_BANK_LTD("Himachal Pradesh State Cooperative Bank Ltd"),
  IDFC_BANK_LTD("IDFC Bank Ltd"),
  ICICI_BANK_LTD("Icici Bank Ltd"),
  IDBI_BANK_LTD("Idbi Bank Ltd"),
  IDUKKI_DISTRICT_COOPERATIVE_BANK_LTD("Idukki District Co-Operative Bank Ltd"),
  INDIA_POST_PAYMENT_BANK("India Post Payment Bank"),
  INDIAN_BANK("Indian Bank"),
  INDIAN_OVERSEAS_BANK("Indian Overseas Bank"),
  INDUSIND_BANK_LTD("Indusind Bank Ltd"),
  INDUSTRIAL_BANK_OF_KOREA("Industrial Bank of Korea"),
  INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LTD("Industrial and Commercial Bank of China Ltd."),
  ING_VYSYA_BANK_LTD("Ing Vysya Bank Ltd"),
  INSTITUTE_FOR_DEV_AND_RESEARCH_IN_BANKING_TECH("Institute for Development and Research in Banking Technology"),
  IRINJALAKUDA_TOWN_COOPERATIVE_BANK_LTD("Irinjalakuda Town Co-Operative Bank Ltd"),
  JALGAON_JANATA_SAHKARI_BANK_LTD("Jalgaon Janata Sahkari Bank Ltd"),
  JAMMU_AND_KASHMIR_BANK_LTD("Jammu And Kashmir Bank Ltd"),
  JANA_SMALL_FINANCE_BANK_LTD("Jana Small Finance Bank Ltd"),
  JANASEVA_SAHAKARI_BANK_BORIVLI_LTD("Janaseva Sahakari Bank Borivli Ltd."),
  JANASEVA_SAHAKARI_BANK_LTD_PUNE("Janaseva Sahakari Bank Ltd Pune"),
  JANATA_SAHKARI_BANK_LTD_PUNE("Janata Sahkari Bank Ltd Pune"),
  JIO_PAYMENTS_BANK_LIMITED("Jio Payments Bank Limited"),
  KEB_HANA_BANK("KEB Hana Bank"),
  KALLAPPANNA_AWADE_ICH_JANATA_S_BANK("Kallappanna Awade Ich Janata S Bank"),
  KALUPUR_COMMERCIAL_CO_OP_BANK_LTD("Kalupur Commercial Co Op Bank Ltd"),
  KALYAN_JANATA_SAHAKARI_BANK_LTD("Kalyan Janata Sahakari Bank Ltd"),
  KARNATAKA_BANK_LTD("Karnataka Bank Ltd"),
  KARNATAKA_STATE_COOP_APEX_BANK_LTD("Karnataka State Co-Op Apex Bank Ltd"),
  KARNATAKA_VIKAS_GRAMEENA_BANK("Karnataka Vikas Grameena Bank"),
  KARUR_VYSYA_BANK("Karur Vysya Bank"),
  KAVERI_GRAMEENA_BANK("Kaveri Grameena Bank"),
  KERALA_GRAMIN_BANK("Kerala Gramin Bank"),
  KOTAK_MAHINDRA_BANK("Kotak Mahindra Bank"),
  KOZHIKODE_DISTRICT_COOPERATIVE_BANK("Kozhikode District Cooperative Bank"),
  KRUNG_THAI_BANK_PCL("Krung Thai Bank PCL"),
  KURMANCHAL_NAGAR_SAHAKARI_BANK_LTD("Kurmanchal Nagar Sahakari Bank Ltd"),
  LAKSHMI_VILAS_BANK_LTD("Lakshmi Vilas Bank Ltd"),
  MAHANAGAR_COOP_BANK_LTD("Mahanagar Co-Op Bank Ltd"),
  MAHARASHTRA_GRAMIN_BANK("Maharashtra Gramin Bank"),
  MAHARASHTRA_STATE_COOP_BANK("Maharashtra State Co-Op Bank"),
  MAHESH_SAHAKARI_BANK_LIMITED_PUNE("Mahesh Sahakari Bank Limited Pune"),
  MASHREQ_BANK_PSC("Mashreq Bank Psc"),
  MEHSANA_URBAN_COOP_BANK_LTD("Mehsana Urban Co-Op Bank Ltd"),
  MUMBAI_DISTRICT_CENTRAL_COOP_BANK_LTD("Mumbai District Central Co-Op Bank Ltd"),
  NSDL_PAYMENTS_BANK_LIMITED("NSDL Payments Bank Limited"),
  NAGAR_URBAN_COOPERATIVE_BANK("Nagar Urban Co-operative Bank"),
  NAGPUR_NAGARIK_SAHAKARI_BANK_LTD("Nagpur Nagarik Sahakari Bank Ltd"),
  NAINITAL_BANK_LTD("Nainital Bank Ltd"),
  NATIONAL_AUSTRALIA_BANK("National Australia Bank"),
  NATIONAL_BANK_FOR_AGRIC_AND_RURAL_DEV("National Bank for Agriculture and Rural Development"),
  NATIONAL_BANK_OF_ABU_DHABI("National Bank of Abu Dhabi"),
  NEW__INDIA_COOP__BANK__LTD("New  India Co-Op  Bank  Ltd"),
  NKGSB_COOP_BANK_LTD("Nkgsb Co-Op Bank Ltd"),
  NORTH_EAST_SMALL_FINANCE_BANK_LTD("North East Small Finance Bank Ltd"),
  NORTH_MALABAR_GRAMIN_BANK("North Malabar Gramin Bank"),
  NUTAN_NAGARIK_SAHAKARI_BANK_LTD("Nutan Nagarik Sahakari Bank Ltd"),
  OMAN_INTERNATIONAL_BANK_SAOG("Oman International Bank Saog"),
  ORIENTAL_BANK_OF_COMMERCE("Oriental Bank Of Commerce"),
  PARSIK_JANATA_SAHAKARI_BANK_LTD("Parsik Janata Sahakari Bank Ltd"),
  PAYTM_PAYMENT_BANK_LTD("Paytm Payment Bank Ltd"),
  PRAGATHI_KRISHNA_GRAMIN_BANK("Pragathi Krishna Gramin Bank"),
  PRATHAMA_BANK("Prathama Bank"),
  PRIME_COOPERATIVE_BANK_LTD("Prime Co-Operative Bank Ltd"),
  PUNJAB_AND_MAHARASHTRA_COOP_BANK_LTD("Punjab And Maharashtra Co-Op Bank Ltd"),
  PUNJAB_AND_SIND_BANK("Punjab And Sind Bank"),
  PUNJAB_NATIONAL_BANK("Punjab National Bank"),
  QATAR_NATOINAL_BANK_SAQ("Qatar Natoinal Bank SAQ"),
  RABOBANK_INTERNATIONAL_CCRB("Rabobank International (CCRB)"),
  RAJARAM_BAPU_SAHAKARI_BANK_LIMITED("Rajaram Bapu Sahakari Bank Limited"),
  RAJASTHAN_MARUDHARA_GRAMIN_BANK("Rajasthan Marudhara Gramin Bank"),
  RAJGURUNAGAR_SAHKARI_BANK_LTD("Rajgurunagar Sahkari Bank Ltd"),
  RAJKOT_NAGARIK_SAHAKARI_BANK_LTD("Rajkot Nagarik Sahakari Bank Ltd"),
  RATNAKAR_BANK_LTD("Ratnakar Bank Ltd"),
  RESERVE_BANK_OF_INDIA("Reserve Bank Of India"),
  ROYAL_BANK_OF_SCOTLAND("Royal Bank Of Scotland"),
  SBER_BANK("SBER Bank"),
  SAMARTH_SAHAKARI_BANK_LTD("Samarth Sahakari Bank Ltd"),
  SARASWAT_COOP_BANK_LTD("Saraswat Co-Op Bank Ltd"),
  SHAMRAO_VITHAL_COOP_BANK_LTD("Shamrao Vithal Co-Op Bank Ltd"),
  SHIKSHAK_SAHKARI_BANK_LTD("Shikshak Sahkari Bank Ltd."),
  SHINHAN_BANK("Shinhan Bank"),
  SHIVALIK_MERCENTILE_COOP_BANK_LTD("Shivalik Mercentile Coop Bank Ltd"),
  SHRI_VEERSHAIV_CO_OP_BANK_LTD("Shri Veershaiv Co Op Bank Ltd"),
  SIR_M_VISVESVARAYA_CO_OPERATIVE_BANK_LIMITED("Sir M Visvesvaraya Co Operative Bank Limited"),
  SMALL_INDUSTRIES_DEVELOPMENT_BANK_OF_INDIA("Small Industries Development Bank of India"),
  SOUTH_INDIAN_BANK("South Indian Bank"),
  STANDARD_CHARTERED_BANK("Standard Chartered Bank"),
  STATE_BANK_OF_BIKANER_AND_JAIPUR("State Bank Of Bikaner And Jaipur"),
  STATE_BANK_OF_HYDERABAD("State Bank Of Hyderabad"),
  STATE_BANK_OF_INDIA("State Bank Of India"),
  STATE_BANK_OF_MAURITIUS_LTD("State Bank Of Mauritius Ltd"),
  STATE_BANK_OF_MYSORE("State Bank Of Mysore"),
  STATE_BANK_OF_PATIALA("State Bank Of Patiala"),
  STATE_BANK_OF_TRAVANCORE("State Bank Of Travancore"),
  SUMITOMO_MITSUI_BANKING_CORPORATION("Sumitomo Mitsui Banking Corporation"),
  SURAT_NATIONAL_COOPERATIVE_BANK("Surat National Co-operative Bank"),
  SURAT_PEOPLES_COOP_BANK_LTD("Surat Peoples Co-Op Bank Ltd"),
  SURYODAY_SMALL_FINANCE_BANK_LIMITED("Suryoday Small Finance Bank Limited"),
  SYNDICATE_BANK("Syndicate Bank"),
  TAMILNAD_MERCANTILE_BANK_LTD("Tamilnad Mercantile Bank Ltd"),
  TAMILNADU_STATE_APEX_COOP_BANK_LTD("Tamilnadu State Apex Co-Op Bank Ltd"),
  TELANGANA_STATE_COOP_APEX_BANK("Telangana State Coop Apex Bank"),
  TEXTILE_TRADERS_CO_OPERATIVE_BANK_LTD("Textile Traders Co Operative Bank Ltd"),
  THANE_BHARAT_SAHAKARI_BANK_LTD("Thane Bharat Sahakari Bank Ltd"),
  THANE_DISTRICT_CENTRAL_COOPERATIVE_BANK_LTD("Thane District Central Co-operative Bank Ltd"),
  THANE_JANATA_SAHAKARI_BANK_LTD("Thane Janata Sahakari Bank Ltd"),
  THE_AP_MAHESH_COOP_URBAN_BANK_LTD("The A.P. Mahesh Co-Op Urban Bank Ltd"),
  THE_AHMEDNAGAR_MERCHANT_COOPERATIVE_BANK("The Ahmednagar Merchant Cooperative Bank"),
  THE_AKOLA_DISTRICT_CENTRAL_COOPERATIVE_BANK("The Akola District Central Co-operative Bank"),
  THE_AKOLA_JANATA_COMMERCIAL_COOPERATIVE_BANK("The Akola Janata Commercial Co-operative Bank"),
  THE_ANDHRA_PRADESH_STATE_COOP_BANK_LTD("The Andhra Pradesh State Co-op Bank Ltd."),
  THE_BARAMATI_SAHAKARI_BANK_LIMITED("The Baramati Sahakari Bank Limited"),
  THE_DELHI_STATE_COOPERATIVE_BANK_LTD("The Delhi State Co-operative Bank Ltd."),
  THE_GADCHIROLI_DISTRICT_CENTRAL_COOP_BANK_LTD("The Gadchiroli District Central Co-operative Bank Ltd"),
  THE_GUJARAT_STATE_COOPERATIVE_BANK_LTD("The Gujarat State Co-Operative Bank Ltd"),
  THE_HARYANA_STATE_COOPERATIVE_APEX_BANK_LTD("The Haryana State Co-operative Apex Bank Ltd"),
  THE_HASTI_COOPERATIVE_BANK_LTD("The Hasti Co-operative Bank Ltd."),
  THE_JALGAON_PEOPLES_COOP_BANK("The Jalgaon Peoples Co-op Bank"),
  THE_KANGRA_CENTRAL_COOPERATIVE_BANK_LTD("The Kangra Central Co-Operative Bank Ltd."),
  THE_KANGRA_COOPERATIVE_BANK_LTD("The Kangra Co-Operative Bank Ltd."),
  THE_KARAD_URBAN_COOP_BANK_LTD("The Karad Urban Co-Op Bank Ltd"),
  THE_MUNICIPAL_COOPERATIVE_BANK_LTD_MUMBAI("The Municipal Co-Operative Bank Ltd. Mumbai"),
  THE_NASIK_MERCHANTS_COOP_BANK_LTD("The Nasik Merchants Co-Op Bank Ltd"),
  THE_NAVNIRMAN_COOPERATIVE_BANK_LIMITED("The Navnirman Co-Operative Bank Limited"),
  THE_PANDHARPUR_URBAN_COOP_BANK_LTD("The Pandharpur Urban Coop Bank Ltd"),
  THE_RAJASTHAN_STATE_COOPERATIVE_BANK_LTD("The Rajasthan State Co-Operative Bank Ltd"),
  THE_SAHEBRAO_DESHMUKH_COOP_BANK_LTD("The Sahebrao Deshmukh Co-op Bank Ltd."),
  THE_SEVA_VIKAS_COOPERATIVE_BANK_LTD("The Seva Vikas Co-operative Bank Ltd"),
  THE_SINDHUDURGA_DISTRICT_CENTRAL_COOP_BANK_LTD("The Sindhudurga District Central COOP Bank Ltd"),
  THE_SOLAPUR_JANATA_SAHKARI_BANK_LTD("The Solapur Janata Sahkari Bank Ltd."),
  THE_SURAT_DISTRICT_COOPERATIVE_BANK_LTD("The Surat District Co-Operative Bank Ltd"),
  THE_URBAN_COOPERATIVE_BANK_LIMITED("The Urban Cooperative Bank Limited"),
  THE_VARACHHA_COOP_BANK_LTD("The Varachha Co-Op. Bank Ltd"),
  THE_VIJAY_CO_OPERATIVE_BANK_LIMITED("The Vijay Co Operative Bank Limited"),
  THE_VISHWESHWAR_SAHAKARI_BANK_LTD_PUNE("The Vishweshwar Sahakari Bank Ltd Pune"),
  THRISSUR_DISTRICT_CO_OPERATIVE_BANK("Thrissur District Co Operative Bank"),
  TUMKUR_GRAIN_MERCHANTS_COOPERATIVE_BANK_LTD("Tumkur Grain Merchants Cooperative Bank Ltd"),
  UBS_AG("UBS AG"),
  UCO_BANK("Uco Bank"),
  UJJIVAN_SMALL_FINANCE_BANK_LIMITED("Ujjivan Small Finance Bank Limited"),
  UNION_BANK_OF_INDIA("Union Bank Of India"),
  UNITED_BANK_OF_INDIA("United Bank Of India"),
  UNITED_OVERSEAS_BANK("United Overseas Bank"),
  UTKARSH_SMALL_FINANCE_BANK("Utkarsh Small Finance Bank"),
  VASAI_JANATA_SAHAKARI_BANK_LIMITED("Vasai Janata Sahakari Bank Limited"),
  VASAI_VIKAS_SAHAKARI_BANK_LTD("Vasai Vikas Sahakari Bank Ltd"),
  VIJAYA_BANK("Vijaya Bank"),
  WEST_BENGAL_STATE_COOP_BANK_LTD("West Bengal State Co-Op Bank Ltd"),
  WESTPAC_BANKING_CORPORATION("Westpac Banking Corporation"),
  WOORI_BANK("Woori Bank"),
  YES_BANK_LTD("Yes Bank Ltd"),
  ZILA_SAHKARI_BANK_LTD_GHAZIABAD("Zila Sahkari Bank Ltd. Ghaziabad"),

  //india bank update
  AJARA_URBAN_CO_OP_BANK_LTD_AJARA("The Ajara Urban Co Op Bank Ltd Ajara"),
  DURGAPUR_STEEL_PEOPLES_CO_OPERATIVE_BANK_LTD("Durgapur Steel Peoples Co-operative Bank Ltd"),
  THE_AKOLA_DISTRICT_CENTRAL_CO_OPERATIVE_BANK("The Akola District Central Cooperative Bank"),
  IDBI_BANK("Idbi Bank"),
  KALYAN_JANATA_SAHAKARI_BANK("Kalyan Janata Sahakari Bank"),
  DOHA_BANK("Doha Bank"),
  ALMORA_URBAN_COOPERATIVE_BANK_LIMITED("Almora Urban Cooperative Bank Limited"),
  JALGAON_JANATA_SAHAKARI_BANK_LIMITED("Jalgaon Janata Sahakari Bank Limited"),
  THE_JALGAON_PEOPELS_COOPERATIVE_BANK_LIMITED("The Jalgaon Peopels Cooperative Bank Limited"),
  THE_KARANATAKA_STATE_COOPERATIVE_APEX_BANK_LIMITED("The Karanataka State Cooperative Apex Bank Limited"),
  THE_AP_MAHESH_COOPERATIVE_URBAN_BANK_LIMITED("The A.p. Mahesh Cooperative Urban Bank Limited"),
  AHMEDABAD_MERCANTILE_COOPERATIVE_BANK("Ahmedabad Mercantile Cooperative Bank"),
  DCB_BANK_LIMITED("Dcb Bank Limited"),
  AUSTRALIA_AND_NEW_ZEALAND_BANKING_GROUP_LIMITED("Australia And New Zealand Banking Group Limited"),
  FEDERAL_BANK("Federal Bank"),
  HARYANA_STATE_COOPERATIVE_BANK("Haryana State Cooperative Bank"),
  JANATA_SAHAKARI_BANK_LIMITED("Janata Sahakari Bank Limited"),
  AHMEDNAGAR_MERCHANTS_COOP_BANK_LTD("Ahmednagar Merchants Co-op Bank Ltd"),
  INDUSIND_BANK("Indusind Bank"),
  BANK_OF_BAHARAIN_AND_KUWAIT_BSC("Bank Of Baharain And Kuwait Bsc"),
  BHAGINI_NIVEDITA_SAHAKARI_BANK_LTD_PUNE("Bhagini Nivedita Sahakari Bank Ltd Pune"),
  IDUKKI_DISTRICT_CO_OPERATIVE_BANK_LTD("Idukki District Co Operative Bank Ltd"),
  HDFC_BANK("Hdfc Bank"),
  DHANALAKSHMI_BANK("Dhanalakshmi Bank"),
  FINO_PAYMENTS_BANK("Fino Payments Bank"),
  JANAKALYAN_SAHAKARI_BANK_LIMITED("Janakalyan Sahakari Bank Limited"),
  CSB_BANK_LIMITED("Csb Bank Limited"),
  THE_KARAD_URBAN_COOPERATIVE_BANK_LIMITED("The Karad Urban Cooperative Bank Limited"),
  KARNATAKA_BANK_LIMITED("Karnataka Bank Limited"),
  CTBC_BANK_CO_LTD("Ctbc Bank Co Ltd"),
  DEOGIRI_NAGARI_SAHAKARI_BANK_LTD_AURANGABAD("Deogiri Nagari Sahakari Bank Ltd. Aurangabad"),
  KOZHIKODE_DISTRICT_COOPERATIAVE_BANK_LTD("Kozhikode District Cooperatiave Bank Ltd"),
  CREDIT_SUISEE_AG("Credit Suisee Ag"),
  DOMBIVLI_NAGARI_SAHAKARI_BANK_LIMITED("Dombivli Nagari Sahakari Bank Limited"),
  ICICI_BANK_LIMITED("Icici Bank Limited"),
  CITIZEN_CREDIT_COOPERATIVE_BANK_LIMITED("Citizen Credit Cooperative Bank Limited"),
  THE_COSMOS_CO_OPERATIVE_BANK_LIMITED("The Cosmos Co Operative Bank Limited"),
  INDIA_CITI_BANK("Citi Bank"),
  THE_GREATER_BOMBAY_COOPERATIVE_BANK_LIMITED("The Greater Bombay Cooperative Bank Limited"),
  KALLAPPANNA_AWADE_ICHALKARANJI_JANATA_SAHAKARI_BANK_LIMITED("Kallappanna Awade Ichalkaranji Janata Sahakari Bank Limited"),
  DBS_BANK_INDIA_LIMITED("Dbs Bank India Limited"),
  THE_GADCHIROLI_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED("The Gadchiroli District Central Cooperative Bank Limited"),
  JANASEVA_SAHAKARI_BANK_LIMITED("Janaseva Sahakari Bank Limited"),
  ABHYUDAYA_COOPERATIVE_BANK_LIMITED("Abhyudaya Cooperative Bank Limited"),
  DEPOSIT_INSURANCE_AND_CREDIT_GUARANTEE_CORPORATION("Deposit Insurance And Credit Guarantee Corporation"),
  APNA_SAHAKARI_BANK_LIMITED("Apna Sahakari Bank Limited"),
  FIRSTRAND_BANK_LIMITED("Firstrand Bank Limited"),
  THE_KANGRA_COOPERATIVE_BANK_LIMITED("The Kangra Cooperative Bank Limited"),
  JAMMU_AND_KASHMIR_BANK_LIMITED("Jammu And Kashmir Bank Limited"),
  DEUSTCHE_BANK("Deustche Bank"),
  HSBC_BANK("Hsbc Bank"),
  KOTAK_MAHINDRA_BANK_LIMITED("Kotak Mahindra Bank Limited"),
  BASSEIN_CATHOLIC_COOPERATIVE_BANK_LIMITED("Bassein Catholic Cooperative Bank Limited"),
  AKOLA_JANATA_COMMERCIAL_COOPERATIVE_BANK("Akola Janata Commercial Cooperative Bank"),
  JP_MORGAN_BANK("Jp Morgan Bank"),
  CITY_UNION_BANK_LIMITED("City Union Bank Limited"),
  BARCLAYS_BANK("Barclays Bank"),
  THE_ANDHRA_PRADESH_STATE_COOPERATIVE_BANK_LIMITED("The Andhra Pradesh State Cooperative Bank Limited"),
  INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LIMITED("Industrial And Commercial Bank Of China Limited"),
  KALUPUR_COMMERCIAL_COOPERATIVE_BANK("Kalupur Commercial Cooperative Bank"),
  THE_GUJARAT_STATE_COOPERATIVE_BANK_LIMITED("The Gujarat State Cooperative Bank Limited"),
  THE_DELHI_STATE_COOPERATIVE_BANK_LIMITED("The Delhi State Cooperative Bank Limited"),
  THE_BARAMATI_SAHAKARI_BANK_LTD("The Baramati Sahakari Bank Ltd"),
  CAPITAL_SMALL_FINANCE_BANK_LIMITED("Capital Small Finance Bank Limited"),
  BHARAT_COOPERATIVE_BANK_MUMBAI_LIMITED("Bharat Cooperative Bank Mumbai Limited"),
  AMBARNATH_JAIHIND_COOP_BANK_LTD_AMBARNATH("Ambarnath Jaihind Coop Bank Ltd Ambarnath"),
  B_N_P_PARIBAS("B N P Paribas"),
  IDFC_FIRST_BANK_LTD("Idfc First Bank Ltd"),
  THE_KURMANCHAL_NAGAR_SAHAKARI_BANK_LIMITED("The Kurmanchal Nagar Sahakari Bank Limited"),
  THE_KERALA_STATE_CO_OPERATIVE_BANK_LTD("The Kerala State Co Operative Bank Ltd"),
  EMIRATES_NBD_BANK_P_J_S_C("Emirates Nbd Bank P J S C"),
  SHRI_CHHATRAPATI_RAJASHRI_SHAHU_URBAN_COOPERATIVE_BANK_LIMITED("Shri Chhatrapati Rajashri Shahu Urban Cooperative Bank Limited"),
  THE_KANGRA_CENTRAL_COOPERATIVE_BANK_LIMITED("The Kangra Central Cooperative Bank Limited"),
  CREDIT_AGRICOLE_CORPORATE_AND_INVESTMENT_BANK_CALYON_BANK("Credit Agricole Corporate And Investment Bank Calyon Bank"),
  EXPORT_IMPORT_BANK_OF_INDIA("Export Import Bank Of India"),
  THE_HASTI_COOP_BANK_LTD("The Hasti Coop Bank Ltd"),
  MUFG_BANK_LTD("Mufg Bank, Ltd"),
  PT_BANK_MAYBANK_INDONESIA_TBK("Pt Bank Maybank Indonesia Tbk"),
  JANASEVA_SAHAKARI_BANK_BORIVLI_LIMITED("Janaseva Sahakari Bank Borivli Limited"),

  //mexico
  BANXICO("BANXICO"),
  BANCOMEXT("BANCOMEXT"),
  BANOBRAS("BANOBRAS"),
  BANJERCITO("BANJERCITO"),
  NAFIN("NAFIN"),
  BANSEFI("BANSEFI"),
  HIPOTECARIA_FED("HIPOTECARIA FED"),
  BANAMEX("BANAMEX"),
  BBVA_BANCOMER("BBVA MEXICO"),
  SANTANDER("SANTANDER"),
  MEX_HSBC("HSBC"),
  BAJIO("BAJIO"),
  INBURSA("INBURSA"),
  MIFEL("MIFEL"),
  SCOTIABANK("SCOTIABANK"),
  BANREGIO("BANREGIO"),
  INVEX("INVEX"),
  BANSI("BANSI"),
  AFIRME("AFIRME"),
  BANORTE_IXE("BANORTE/IXE"),
  BAMSA("BAMSA"),
  MEX_TOKYO("TOKYO"),
  JP_MORGAN("JP MORGAN"),
  BMONEX("BMONEX"),
  VE_POR_MAS("VE POR MAS"),
  MEX_DEUTSCHE("DEUTSCHE"),
  CREDIT_SUISSE("CREDIT SUISSE"),
  AZTECA("AZTECA"),
  AUTOFIN("AUTOFIN"),
  BARCLAYS("BARCLAYS"),
  COMPARTAMOS("COMPARTAMOS"),
  MULTIVA_BANCO("MULTIVA BANCO"),
  ACTINVER("ACTINVER"),
  INTERCAM_BANCO("INTERCAM BANCO"),
  BANCOPPEL("BANCOPPEL"),
  ABC_CAPITAL("ABC CAPITAL"),
  CONSUBANCO("CONSUBANCO"),
  VOLKSWAGEN("VOLKSWAGEN"),
  CIBANCO("CIBANCO"),
  BBASE("BBASE"),
  BANKAOOL("BANKAOOL"),
  PAGATODO("PAGATODO"),
  INMOBILIARIO("INMOBILIARIO"),
  DONDE("DONDE"),
  BANCREA("BANCREA"),
  BANCO_FINTERRA("BANCO FINTERRA"),
  MEX_ICBC("ICBC"),
  SABADELL("SABADELL"),
  MIZUHO_BANK("MIZUHO BANK"),
  MONEXCB("MONEXCB"),
  GBM("GBM"),
  MASARI("MASARI"),
  VALUE("VALUE"),
  ESTRUCTURADORES("ESTRUCTURADORES"),
  VECTOR("VECTOR"),
  MULTIVA_CBOLSA("MULTIVA CBOLSA"),
  FINAMEX("FINAMEX"),
  VALMEX("VALMEX"),
  PROFUTURO("PROFUTURO"),
  CB_INTERCAM("CB INTERCAM"),
  CI_BOLSA("CI BOLSA"),
  FINCOMUN("FINCOMUN"),
  AKALA("NU MEXICO"),
  REFORMA("REFORMA"),
  STP("STP"),
  EVERCORE("TACTIV CB"),
  ASEA("ASEA"),
  KUSPIT("KUSPIT"),
  UNAGRA("UNAGRA"),
  ASP_INTEGRA_OPC("ASP INTEGRA OPC"),
  LIBERTAD("LIBERTAD"),
  CAJA_POP_MEXICA("CAJA POP MEXICA"),
  CRISTOBAL_COLON("CRISTOBAL COLON"),
  CAJA_TELEFONIST("CAJA TELEFONIST"),
  TRANSFER("TRANSFER"),
  FONDO_FIRA("FONDO (FIRA)"),
  INVERCAP("INVERCAP"),
  FOMPED("FOMPED"),
  INDEVAL("INDEVAL"),
  SHINHAN_MEX("SHINHAN"),
  BANCO_S3("BANCO S3"),
  CODI_VALIDA("CoDi Valida"),
  ARCUS("ARCUS"),
  BULLTICK_CB("BULLTICK CB"),
  UNICA("UNICA"),
  TELECOMM("TELECOMM"),
  STERLING("STERLING"),
  SEGMTY("SEGMTY"),
  BMULTIVA("BMULTIVA"),
  MERRILL_LYNCH("MERRILL LYNCH"),
  OACTIN("OACTIN"),
  AMERICAN_EXPRESS("AMERICAN EXPRESS"),
  MAPFRE("MAPFRE"),
  OPCIONES_EMPRESARIALES_DEL_NOROESTE("OPCIONES EMPRESARIALES DEL NOROESTE"),
  BB("B&B"),
  TIBER("TIBER"),
  INTERCAM("INTERCAM"),
  SU_CASITA("SU CASITA"),
  UBS_BANK("UBS BANK"),
  WAL_MART("WAL-MART"),
  THE_ROYAL_BANK("THE ROYAL BANK"),
  ING("ING"),
  NA("N/A"),
  BANK_OF_CHINA("BANK OF CHINA"),
  ALTERNATIVOS("ALTERNATIVOS"),
  CREDICLUB("CREDICLUB"),
  TESORED("TESORED"),
  NVIO("NVIO"),

  // Poland
  POL_KONTO_BANK("KontoBank"), // KontoBank, test env only
  POL_ING("ING Bank Śląski"),
  POL_SBP("Santander Bank Polska"),
  POL_PKO_BP("PKO BP"),
  POL_M_BANK("mBank"),
  POL_BMSA("Bank Millennium S.A."),
  POL_ALIOR("Alior Bank"),
  POL_BNP("BNP Paribas (GOonline)"),
  POL_BANK_POCZTOWY("Bank Pocztowy"),
  POL_CREDIT_AGRICOLE("Crédit Agricole"),
  POL_VELO_BANK("VeloBank"),
  POL_NEST_BANK("Nest Bank"),
  POL_BOS("Bank Ochrony Środowiska (BOŚ)"),

  //to be deleted
  INTERACCIONES("INTERACCIONES"),
  ACCENDO_BANCO("ACCENDO BANCO"),
  AMERICAN_EXPRES("AMERICAN EXPRES"),
  BANCO_FAMSA("BANCO FAMSA"),
  ACCIVAL("ACCIVAL"),
  CB_ACTINVER("CB ACTINVER"),
  SKANDIA("SKANDIA"),
  CBDEUTSCHE("CBDEUTSCHE"),
  ZURICH("ZURICH"),
  ZURICHVI("ZURICHVI"),
  HDI_SEGUROS("HDI SEGUROS"),
  ORDER("ORDER"),
  CB_JPMORGAN("CB JPMORGAN"),
  OSKNDIA("OSKNDIA"),
  SOFIEXPRESS("SOFIEXPRESS"),
  HUASTECAS("HUASTECAS"),
  AXA("AXA"),
  SURA("SURA"),
  FND("FND"),
  INFONAVIT("INFONAVIT"),
  CLS("CLS"),
  BBVA_BANCOMER2("BBVA BANCOMER2"),
  SANTANDER2("SANTANDER2"),
  HSBC2("HSBC2"),
  UNKOWN("unknown"),
  YQG_BANK("YQG TEST BANK"),
  YQG_E_WALLET("YQG TEST E-WALLET", true),
  DEFAULT("DEFAULT FOR SUPPORTED BANK LIST API"),
  ;

  public String description;

  public boolean isEWallet;

  public static final List<BankType> IDN_EWALLET_LIST = ImmutableList.of(DANA, GO_PAY, OVO, SHOPEE_PAY, LINKAJA);

  public static final List<BankType> IDN_BANK_LIST = ImmutableList.of();


  public static final List<BankType> FUZZY_NAME_BANK_LIST = ImmutableList.of(DANA, OVO, SHOPEE_PAY);

  BankType(String description) {
    this(description, false);
  }

  BankType(String description, boolean isEWallet) {
    this.description = description;
    this.isEWallet = isEWallet;
  }

  public static BankType valueOfOrNull(String name) {
    try {
      return valueOf(name);
    } catch (Exception e) {
      log.error("can't convert to bank_type. bank: {}", name, e);
    }
    return null;
  }

  public static BankType fromDescIgnoreCase(String desc) {
    for (BankType bankType : BankType.values()) {
      if (bankType.description.equalsIgnoreCase(desc)) {
        return bankType;
      }
    }
    log.error("can't convert to bank_type. bank desc: {}", desc);
    return null;
  }

  public static List<BankType> ofProvider(PaymentProvider paymentProvider) {
    switch (paymentProvider) {
      case XENDIT_IDN:
        return xenditBankTypes();
      case INSTAMONEY:
        return instamoneyBankTypes();
      default:
        return ImmutableList.of();
    }
  }

  private static List<BankType> instamoneyBankTypes() {
    //TODO(Hafiz: complete the list)
    return ImmutableList.of();
  }

  private static List<BankType> xenditBankTypes() {
    //TODO(Hafiz: complete the list)
    return ImmutableList.of();
  }

  public boolean isIdnEWalletType() {
    return IDN_EWALLET_LIST.contains(this);
  }
}